name: Andrewmccracken
favicon: null
layout_spectrum: 0.4147940219845623
typography_spectrum: 0.3759959004819393
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6142059464473277
  lightness: 0.3225411754101515
  saturation: 0.9498592910822481
  rhythmicContrast: 0.5959199983626604
purpose: []
